apiVersion: v1
kind: ConfigMap
metadata:
  name: tcb-trino-coordinator
  namespace: dados
  labels:
    app: trino
    chart: trino-0.2.0
    release: tcb
    heritage: Helm
    component: coordinator
data:
  node.properties: |
    node.environment=production
    node.data-dir=/data/trino
    plugin.dir=/usr/lib/trino/plugin

  jvm.config: |
    -server
    -Xmx8G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -Djdk.attach.allowAttachSelf=true
    -XX:-UseBiasedLocking
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.nio.maxCachedBufferSize=2000000

  config.properties: |
    coordinator=true
    http-server.https.enabled=true
    http-server.http.port=8080
    http-server.authentication.type=PASSWORD 
    internal-communication.shared-secret=UJfeLZicUqYA+0MyftrbgZIb0YaKbDELfoUj1Dvxvp4=
    internal-communication.https.required=true
    query.max-memory=4GB
    query.max-memory-per-node=1GB
    memory.heap-headroom-per-node=1GB
    node-scheduler.include-coordinator=true
    discovery-server.enabled=true
    discovery.uri=http://localhost:8080

  access-control.properties: |
    access-control.name=file
    security.config-file=etc/trino/rules.json
    security.refresh-period=30s

  group-provider.properties: | 
    group-provider.name=file
    file.group-file=etc/trino/secgroup.txt
    file.refresh-period=30s

  password-authenticator.properties: |
    password-authenticator.name=file
    file.password-file=etc/trino/psw.db

  secgroup.txt: |
    gp_adm:destaxa,admin
    gp_user:amilton

  rules.json: |
    {
      "catalogs": [
      {
        "role": "admin",
        "catalog": ".*",
        "allow": "all"
      },
      {
        "group": "gp_adm",
        "catalog": ".*",
        "allow": "all"
      },
      {
        "group": "gp_user",
        "catalog": ".*",
        "allow": "all"
      },
      {
        "catalog": "system",
        "allow": "all"
      }
     ],
      "schemas": [
      {
        "role": "admin",
        "schema": ".*",
        "owner": true
      },
      {
        "group": "gp_user",
        "schema": ".*",
        "owner": true
      }
     ],
      "tables": [
       {
          "role": "admin",
          "privileges": ["SELECT","INSERT","DELETE","UPDATE","OWNERSHIP"]
       },
       {
          "group": "gp_adm",
          "table": ".*",      
          "privileges": ["SELECT","INSERT","DELETE","UPDATE","OWNERSHIP"]
       },
       {
          "group": "gp_user",
          "table": ".*",      
          "privileges": ["SELECT","INSERT","DELETE","UPDATE","OWNERSHIP"]
       }
     ] 
    }
    
  psw.db: |
    amilton:$2y$10$TZF3iBqcYeDSVR1VtB9x.ul40u8ZkmfiyPk4eS5d3aH8reEeF4Vfa
    destaxa:$2y$10$7ro.Rp6rS7HkxN6Ej3K1CutS/dpXwZ6lCwONnN3o2yPQ3.bLjjkYK
    admin:$2y$08$OQTumJpVAPYKfMTfPJ7dwuRaK0S4wMRQDKuPaMWnwpKJAxkvBti9e

  log.properties: |
    io.trino=INFO

