apiVersion: v1
kind: ConfigMap
metadata:
  name: tcb-trino-catalog
  namespace: dados
  labels:
    app: trino
    chart: trino-0.2.0
    release: tcb
    heritage: Helm
    role: catalogs
data:
  tpch.properties: |
    connector.name=tpch
    tpch.splits-per-node=4
  tpcds.properties: |
    connector.name=tpcds
    tpcds.splits-per-node=4
  mongodb.properties: |
    connector.name=mongodb
    mongodb.connection-url=mongodb://mongodb.default.svc:27017/
